# Generated by Django 5.2.3 on 2025-07-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact_delete_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user_document',
        ),
    ]
